cluster.name: "docker-cluster"
network.host: 0.0.0.0

# https://www.elastic.co/guide/en/elasticsearch/reference/current/important-settings.html

# https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-configuration-memory.html#mlockall
bootstrap.memory_lock: true

discovery.zen.minimum_master_nodes: 1
cluster.initial_master_nodes:
  - es-master

## below are some of the options I used to use for performance tuning
## TODO: make sure to find the corresponding documentation on below configs

#memory
indices.fielddata.cache.size: 20%

#index
thread_pool.write.queue_size: 3000

action.destructive_requires_name: true
